import { Inter } from 'next/font/google'
import './globals.css'

import Footer from '@/components/Footer'
import Navbar from '@/components/Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[url('https://images.unsplash.com/photo-1614313913007-2b4ae8ce32d6?q=80&w=2874&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D')] bg-cover`}>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  )
}
