import { Inter, Maven_Pro} from 'next/font/google'
import { Inconsolata } from "next/font/google"
import { ClerkProvider, auth } from '@clerk/nextjs'
import './globals.css'
import Nav from '@/components/Nav'
import { userSignedUp } from '@/utils/utils'
import { redirect } from "next/navigation"

const inconsolata = Inconsolata({subsets: ['latin']})
const inter = Inter({ subsets: ['latin'] })
export const maven_pro = Maven_Pro({subsets: ['latin']})

export const metadata = {
  title: 'Sams Books',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {

  // console.log(userI)
  // const isUserSignedUp = await userSignedUp(userId)
  // if (!isUserSignedUp) {
  //   redirect('/users/sign-up', 'push')
  // }
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inconsolata.className}>
        <Nav />
        {children}
      </body>
    </html>
    </ClerkProvider>
  )
}
