import { Inter, Maven_Pro} from 'next/font/google'
import { Inconsolata } from "next/font/google"
import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import Nav from '@/components/Nav'


const inconsolata = Inconsolata({subsets: ['latin']})
const inter = Inter({ subsets: ['latin'] })
export const maven_pro = Maven_Pro({subsets: ['latin']})

export const metadata = {
  title: 'Sams Books',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inconsolata.className}>
        <Nav />
        {children}
      </body>
    </html>
    </ClerkProvider>
  )
}
